version: "3.9"
services:
  student-app:
    build: .
    ports:
      - "8443:8443"
    volumes:
      - h2-data:/data
    networks:
      - myapp-network

volumes:
  h2-data:
    driver: local

networks:
  myapp-network:
    driver: bridge
